
server:
  port: 9090
#  servlet:
#    context-path: /aa
#spring:
#    devtools:
#        restart:
#            #热部署生效
#          enabled: true
#            #设置重启的目
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
#  profiles:
#    active: dev
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  type-aliases-package: com.zhao.demo.bean
  mapper-locations: classpath:mapper/*.xml
#打印日志
logging:
  level:
   zhao.demo.mapper: debug
   web:
    DEBUG

#spring.thymeleaf.cache=false

#开发阶段，建议关闭thymeleaf的缓
#logging:
#  level:
#    root: debug

#school:
#  name: 小猴子
#  address: 北京
#  age: 101
#server:
#  port: 8082
#info:
#  author: monkey1024
#  url: www.monkey1024.com
#management:
#  server:
#    port: 8081
#  endpoints:
#    web:
#      exposure:
#        include: *
