server:
  port: 6010
spring:
  application:
    name: demosoauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://192.168.211.132:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 172.16.147.184
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#打印日志
logging:
  level:
   com.cloud: debug
#mybatis的配置 可以不配置  需要整合通用mapper
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.changgou.goods.pojo