server:
  port: 18040
spring:
  application:
    name: spring-cloud-config-center
  cloud:
    config:
      server:
        git: # git仓库
          uri: https://github.com/yyyyjinying/spring-cloud-config.git
          search-paths: # 搜索目录
            - spring-cloud-config # 指定仓库
          username: yyyyjinying
          password: Jinying3818
      label: main
  rabbitmq:
    host: 172.16.147.184 # 虚拟机IP
    port: 5672
    username: mm
    password: 123456
      # http://localhost:18040/config/dev/main
      # http://localhost:18040/main/config-dev.yml

# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

#management: # rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"  # curl -X POST "http://localhost:18040/actuator/bus-refresh"