server:
  port: 18040
spring:
  application:
    name: spring-cloud-config-center
  cloud:
    config:
      server:
        git: # git仓库
          uri: https://github.com/yyyyjinying/spring-cloud-config.git
          search-paths: # 搜索目录
            - spring-cloud-config # 指定仓库
          username: yyyyjinying
          password: Jinying3818
      label: main # 指定分支
      # http://localhost:18040/config/dev/main
      # http://localhost:18040/main/config-dev.yml

# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
#management:
#  endpoint:
#    gateway:
#      enabled: true
#    web:
#      exposure:
#        include: true
